### ISSUE TITLE
Unable to use $this->execute inside an artisan command

### ISSUE THREAD

**Issue by lucacri** [laracasts/Commander#23]
Hi,
i'm trying to use the CommanderTrait inside an artisan command, but i receive the following error:
`{"error":{"type":"ErrorException","message":"Declaration of Laracasts\\Commander\\CommanderTrait::execute() should be compatible with Illuminate\\Console\\Command::execute(Symfony\\Component\\Console\\Input\\InputInterface $input, Symfony\\Component\\Console\\Output\\OutputInterface $output)","file":"\/Users\/lucacri\/Sites\/YodaImporter\/app\/commands\/ReassignVncPorts.php","line":77}}`

From what i can see, the `Illuminate\Console\Command` has already an `execute` method in line 110:
`protected function execute(InputInterface $input, OutputInterface $output)` 

and it's not working well with the CommanderTrait. Any suggestion on how to fix it?

**Comment by ghost** [comment]
Has anyone solved this?

**Comment by ghost** [comment]
See https://laracasts.com/discuss/channels/general-discussion/laracasts-commander-with-artisan-commands

I used the answer given there but don't use the Trait.
